spring:
  application:
    name: ws_flexjunction_user_management
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        id:
          new_generator_mappings: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

flex-junction:
  user-management:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/USERS?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      user: root
      password: $7-pL_NzDDd43!p&
  confirmation-email:
    email: parkerharrelson13@gmail.com


server:
  servlet:
    context-path: /ws_flexjunction_user_management
  port: 8080

